const { addTranslations } = require('./addTranslations.cjs');

const en = {
  "profile.title": "My Profile",
  "profile.subtitle": "Manage your personal information",
  "profile.full_name": "Full Name",
  "profile.email_address": "Email Address",
  "profile.contact_number": "Contact Number",
  "profile.location": "Location / Address",
  "profile.bio": "Bio / Description",
  "profile.save": "Save Profile",
  
  "settings.title": "Settings",
  "settings.subtitle": "Manage your preferences and application settings.",
  "settings.general": "General",
  "settings.notifications": "Notifications",
  "settings.privacy": "Privacy & Security",
  "settings.sign_out": "Sign Out",
  "settings.appearance": "Appearance",
  "settings.appearance_desc": "Customize how the application looks on your device.",
  "settings.theme_pref": "Theme Preference",
  "settings.theme_desc": "Toggle between light and dark mode.",
  "settings.light_mode": "Light Mode",
  "settings.dark_mode": "Dark Mode",
  "settings.language": "Language & Region",
  "settings.language_desc": "Choose your preferred language for the interface.",
  "settings.notification_pref": "Notification Preferences",
  "settings.notification_desc": "Control what alerts you receive and how.",
  "settings.email_notif": "Email Notifications",
  "settings.email_notif_desc": "Receive updates about your account and activity via email.",
  "settings.push_notif": "Push Notifications",
  "settings.push_notif_desc": "Get real-time alerts in your browser when you have new messages.",
  "settings.promo_notif": "Promotional Offers",
  "settings.promo_notif_desc": "Receive emails about special offers and nearby discounts.",
  
  "forgot.title": "Reset Password",
  "forgot.sent_desc": "Check your email for the reset link",
  "forgot.form_desc": "Enter your email to receive a password reset link",
  "forgot.sending": "Sending link...",
  "forgot.send_link": "Send Reset Link",
  "forgot.return_login": "Return to Login",
  "forgot.remembered": "Remembered your password?",
  
  "update.title": "Update Password",
  "update.subtitle": "Please enter your new password below.",
  "update.new_password": "New Password",
  "update.confirm_password": "Confirm New Password",
  "update.updating": "Updating...",
  
  "notfound.title": "Page Not Found",
  "notfound.desc": "Oops! The page you are looking for doesn't exist or has been moved. Let's get you back on track.",
  "notfound.back": "Back to Homepage",
  "loading": "Loading..."
};

const hi = {
  "profile.title": "मेरी प्रोफ़ाइल",
  "profile.subtitle": "अपनी व्यक्तिगत जानकारी प्रबंधित करें",
  "profile.full_name": "पूरा नाम",
  "profile.email_address": "ईमेल पता",
  "profile.contact_number": "संपर्क नंबर",
  "profile.location": "स्थान / पता",
  "profile.bio": "परिचय / विवरण",
  "profile.save": "प्रोफ़ाइल सहेजें",
  
  "settings.title": "सेटिंग्स",
  "settings.subtitle": "अपनी प्राथमिकताएं और एप्लिकेशन सेटिंग्स प्रबंधित करें।",
  "settings.general": "सामान्य",
  "settings.notifications": "सूचनाएं",
  "settings.privacy": "गोपनीयता और सुरक्षा",
  "settings.sign_out": "साइन आउट करें",
  "settings.appearance": "दिखावट",
  "settings.appearance_desc": "कस्टमाइज़ करें कि एप्लिकेशन आपके डिवाइस पर कैसा दिखता है।",
  "settings.theme_pref": "थीम प्राथमिकता",
  "settings.theme_desc": "लाइट और डार्क मोड के बीच टॉगल करें।",
  "settings.light_mode": "लाइट मोड",
  "settings.dark_mode": "डार्क मोड",
  "settings.language": "भाषा और क्षेत्र",
  "settings.language_desc": "इंटरफ़ेस के लिए अपनी पसंदीदा भाषा चुनें।",
  "settings.notification_pref": "अधिसूचना प्राथमिकताएं",
  "settings.notification_desc": "नियंत्रित करें कि आपको कौन से अलर्ट और कैसे प्राप्त होते हैं।",
  "settings.email_notif": "ईमेल सूचनाएं",
  "settings.email_notif_desc": "ईमेल के माध्यम से अपने खाते और गतिविधि के बारे में अपडेट प्राप्त करें।",
  "settings.push_notif": "पुश सूचनाएं",
  "settings.push_notif_desc": "जब आपके पास नए संदेश हों तो अपने ब्राउज़र में रीयल-टाइम अलर्ट प्राप्त करें।",
  "settings.promo_notif": "प्रचार प्रस्ताव",
  "settings.promo_notif_desc": "विशेष प्रस्तावों और आस-पास की छूट के बारे में ईमेल प्राप्त करें।",
  
  "forgot.title": "पासवर्ड रीसेट करें",
  "forgot.sent_desc": "रीसेट लिंक के लिए अपना ईमेल जांचें",
  "forgot.form_desc": "पासवर्ड रीसेट लिंक प्राप्त करने के लिए अपना ईमेल दर्ज करें",
  "forgot.sending": "लिंक भेजा जा रहा है...",
  "forgot.send_link": "रीसेट लिंक भेजें",
  "forgot.return_login": "लॉगिन पर लौटें",
  "forgot.remembered": "क्या आपको अपना पासवर्ड याद है?",
  
  "update.title": "पासवर्ड अपडेट करें",
  "update.subtitle": "कृपया नीचे अपना नया पासवर्ड दर्ज करें।",
  "update.new_password": "नया पासवर्ड",
  "update.confirm_password": "नये पासवर्ड की पुष्टि करें",
  "update.updating": "अपडेट हो रहा है...",
  
  "notfound.title": "पृष्ठ नहीं मिला",
  "notfound.desc": "उफ़! आप जिस पृष्ठ को ढूंढ रहे हैं वह मौजूद नहीं है या स्थानांतरित कर दिया गया है। आइए आपको वापस रास्ते पर लाएं।",
  "notfound.back": "होमपेज पर वापस जाएं",
  "loading": "लोड हो रहा है..."
};

const mr = {
  "profile.title": "माझी प्रोफाइल",
  "profile.subtitle": "तुमची वैयक्तिक माहिती व्यवस्थापित करा",
  "profile.full_name": "पूर्ण नाव",
  "profile.email_address": "ईमेल पत्ता",
  "profile.contact_number": "संपर्क क्रमांक",
  "profile.location": "स्थान / पत्ता",
  "profile.bio": "बायो / वर्णन",
  "profile.save": "प्रोफाइल सेव्ह करा",
  
  "settings.title": "सेटिंग्ज",
  "settings.subtitle": "तुमची प्राधान्ये आणि अनुप्रयोग सेटिंग्ज व्यवस्थापित करा.",
  "settings.general": "सामान्य",
  "settings.notifications": "सूचना",
  "settings.privacy": "गोपनीयता आणि सुरक्षा",
  "settings.sign_out": "साइन आउट करा",
  "settings.appearance": "देखावा",
  "settings.appearance_desc": "तुमच्या डिव्हाइसवर अनुप्रयोग कसा दिसतो ते सानुकूलित करा.",
  "settings.theme_pref": "थीम प्राधान्य",
  "settings.theme_desc": "लाइट आणि डार्क मोड दरम्यान टॉगल करा.",
  "settings.light_mode": "लाइट मोड",
  "settings.dark_mode": "डार्क मोड",
  "settings.language": "भाषा आणि प्रदेश",
  "settings.language_desc": "इंटरफेससाठी तुमची पसंतीची भाषा निवडा.",
  "settings.notification_pref": "सूचना प्राधान्ये",
  "settings.notification_desc": "तुम्हाला कोणते अलर्ट आणि कसे मिळतात ते नियंत्रित करा.",
  "settings.email_notif": "ईमेल सूचना",
  "settings.email_notif_desc": "ईमेलद्वारे तुमच्या खात्याविषयी आणि क्रियाकलापांबद्दल अद्यतने मिळवा.",
  "settings.push_notif": "पुश सूचना",
  "settings.push_notif_desc": "तुमच्याकडे नवीन संदेश असताना तुमच्या ब्राउझरमध्ये रिअल-टाइम अलर्ट मिळवा.",
  "settings.promo_notif": "प्रचारात्मक ऑफर",
  "settings.promo_notif_desc": "विशेष ऑफर आणि जवळच्या सवलतींबद्दल ईमेल प्राप्त करा.",
  
  "forgot.title": "पासवर्ड रीसेट करा",
  "forgot.sent_desc": "रीसेट लिंकसाठी तुमचा ईमेल तपासा",
  "forgot.form_desc": "पासवर्ड रीसेट लिंक प्राप्त करण्यासाठी तुमचा ईमेल प्रविष्ट करा",
  "forgot.sending": "लिंक पाठवत आहे...",
  "forgot.send_link": "रीसेट लिंक पाठवा",
  "forgot.return_login": "लॉगिनवर परत जा",
  "forgot.remembered": "तुमचा पासवर्ड आठवला का?",
  
  "update.title": "पासवर्ड अपडेट करा",
  "update.subtitle": "कृपया खाली तुमचा नवीन पासवर्ड प्रविष्ट करा.",
  "update.new_password": "नवीन पासवर्ड",
  "update.confirm_password": "नवीन पासवर्डची पुष्टी करा",
  "update.updating": "अपडेट करत आहे...",
  
  "notfound.title": "पृष्ठ आढळले नाही",
  "notfound.desc": "अरेरे! तुम्ही शोधत असलेले पृष्ठ अस्तित्वात नाही किंवा हलवले गेले आहे. चला तुम्हाला परत मार्गावर आणूया.",
  "notfound.back": "मुखपृष्ठावर परत जा",
  "loading": "लोड करत आहे..."
};

addTranslations(en, hi, mr);
