const { addTranslations } = require('./addTranslations.cjs');

const en = {
  "user.discover_services": "Discover Services",
  "user.find_best_rated": "Find the best-rated shops near you",
  "user.search_placeholder": "Search for Xerox, Tailor, or other stores...",
  "user.any_price": "Any Price",
  "Any Rating": "Any Rating",
  "Stars": "Stars",
  "Top Pick": "Top Pick",
  "shop.open_now": "Open Now",
  "shop.closed": "Closed",
  "Location unavailable": "Location unavailable",
  "km from you": "km from you",
  "km from city center": "km from city center",
  "market": "market",
  "reviews": "reviews",
  "Get Directions": "Get Directions",
  "Locate": "Locate",
  "Call Now": "Call Now",
  "Leave Feedback": "Leave Feedback",
  "user.no_matches_found": "No matches found",
  "user.no_matches_subtitle": "We couldn't find any services matching your specific filters. Try adjusting them.",
  "Clear All Filters": "Clear All Filters",
  "Your Location": "Your Location",
  "Searching nearby...": "Searching nearby...",
  "New": "New",
  "user.rate": "Rate",
  "user.feedback_desc": "Your feedback directly influences the recommendation engine.",
  "user.your_rating": "Your Rating",
  "user.write_review": "Write a Review",
  "user.review_placeholder": "Tell us about your experience...",
  "Cancel": "Cancel",
  "Submit": "Submit"
};

const hi = {
  "user.discover_services": "सेवाएं खोजें",
  "user.find_best_rated": "अपने आस-पास सर्वश्रेष्ठ रेटिंग वाली दुकानें खोजें",
  "user.search_placeholder": "ज़ेरॉक्स, दर्जी, या अन्य स्टोर खोजें...",
  "user.any_price": "कोई भी कीमत",
  "Any Rating": "कोई भी रेटिंग",
  "Stars": "सितारे",
  "Top Pick": "शीर्ष पसंद",
  "shop.open_now": "अभी खुला है",
  "shop.closed": "बंद",
  "Location unavailable": "स्थान उपलब्ध नहीं है",
  "km from you": "किमी दूर",
  "km from city center": "शहर के केंद्र से किमी दूर",
  "market": "बाजार",
  "reviews": "समीक्षाएं",
  "Get Directions": "दिशा-निर्देश प्राप्त करें",
  "Locate": "पता लगाएं",
  "Call Now": "अभी कॉल करें",
  "Leave Feedback": "प्रतिक्रिया दें",
  "user.no_matches_found": "कोई मेल नहीं मिला",
  "user.no_matches_subtitle": "हमें आपके विशिष्ट फ़िल्टर से मेल खाने वाली कोई सेवा नहीं मिली। उन्हें समायोजित करने का प्रयास करें।",
  "Clear All Filters": "सभी फ़िल्टर साफ़ करें",
  "Your Location": "आपका स्थान",
  "Searching nearby...": "आस-पास खोजा जा रहा है...",
  "New": "नया",
  "user.rate": "रेट करें",
  "user.feedback_desc": "आपकी प्रतिक्रिया सीधे अनुशंसा इंजन को प्रभावित करती है।",
  "user.your_rating": "आपकी रेटिंग",
  "user.write_review": "समीक्षा लिखें",
  "user.review_placeholder": "हमें अपने अनुभव के बारे में बताएं...",
  "Cancel": "रद्द करें",
  "Submit": "जमा करें"
};

const mr = {
  "user.discover_services": "सेवा शोधा",
  "user.find_best_rated": "तुमच्या जवळील सर्वोत्तम रेट केलेली दुकाने शोधा",
  "user.search_placeholder": "झेरॉक्स, शिंपी किंवा इतर दुकाने शोधा...",
  "user.any_price": "कोणतीही किंमत",
  "Any Rating": "कोणतेही रेटिंग",
  "Stars": "तारे",
  "Top Pick": "सर्वोत्तम निवड",
  "shop.open_now": "आता खुले आहे",
  "shop.closed": "बंद",
  "Location unavailable": "स्थान उपलब्ध नाही",
  "km from you": "किमी दूर",
  "km from city center": "शहराच्या केंद्रापासून किमी दूर",
  "market": "बाजार",
  "reviews": "पुनरावलोकने",
  "Get Directions": "दिशा मिळवा",
  "Locate": "शोधा",
  "Call Now": "आता कॉल करा",
  "Leave Feedback": "प्रतिक्रिया द्या",
  "user.no_matches_found": "काहीही जुळले नाही",
  "user.no_matches_subtitle": "तुमच्या विशिष्ट फिल्टरशी जुळणारी कोणतीही सेवा आम्हाला आढळली नाही. त्यांना समायोजित करण्याचा प्रयत्न करा.",
  "Clear All Filters": "सर्व फिल्टर साफ करा",
  "Your Location": "तुमचे स्थान",
  "Searching nearby...": "जवळपास शोधत आहे...",
  "New": "नवीन",
  "user.rate": "रेट करा",
  "user.feedback_desc": "तुमचा अभिप्राय थेट शिफारस इंजिनवर प्रभाव टाकतो.",
  "user.your_rating": "तुमचे रेटिंग",
  "user.write_review": "पुनरावलोकन लिहा",
  "user.review_placeholder": "आम्हाला तुमच्या अनुभवाबद्दल सांगा...",
  "Cancel": "रद्द करा",
  "Submit": "सबमिट करा"
};

addTranslations(en, hi, mr);
