const { addTranslations } = require('./addTranslations.cjs');

const en = {
  "landing.smart_recommendation": "Smart Service Recommendation System",
  "landing.find_perfect_service": "Find the perfect service",
  "landing.near_you_instantly": "near you, instantly.",
  "landing.hero_subtitle": "Servease helps you discover top-rated tailors, xerox shops, mechanics, and laundry services. We analyze price, distance, and ratings to recommend the absolute best option.",
  "landing.go_to_dashboard": "Go to Dashboard",
  "landing.get_started_now": "Get Started Now",
  "landing.login_to_account": "Login to Account",
  "landing.top_rated_services": "Top Rated Services",
  "landing.join_today_subtitle": "Join today to book or review these amazing local shops.",
  "landing.top_pick": "Top Pick",
  "shop.reviews": "reviews",
  "shop.away": "away",
  "landing.login_to_view": "Login to view",
  "landing.feature_1_title": "Smart Discovery",
  "landing.feature_1_desc": "Our algorithm ranks shops by balancing distance, price, and customer reviews.",
  "landing.feature_2_title": "Trusted Reviews",
  "landing.feature_2_desc": "Real reviews from local customers help you make the best decision.",
  "landing.feature_3_title": "Grow Your Business",
  "landing.feature_3_desc": "Shopkeepers can easily list their services and attract nearby customers.",
  "landing.how_it_works": "How It Works",
  "landing.step1_title": "Search Services",
  "landing.step1_desc": "Find local shops and services around your current location instantly.",
  "landing.step2_title": "Compare & Choose",
  "landing.step2_desc": "Compare prices, distance, and read genuine reviews from neighbors.",
  "landing.step3_title": "Connect Easily",
  "landing.step3_desc": "Get directions or contact the shopkeeper directly to get your work done.",
  "landing.about_title": "Empowering Local Communities",
  "landing.about_desc": "Servease was born out of a simple idea: to bridge the gap between skilled local professionals and people who need them. We believe in strengthening neighborhood economies by making local services accessible, transparent, and completely hassle-free.",
  "landing.stat_shops": "Local Shops",
  "landing.stat_users": "Happy Users",
  "landing.stat_cities": "Cities Active",
  "landing.stat_rating": "App Rating"
};

const hi = {
  "landing.smart_recommendation": "स्मार्ट सेवा अनुशंसा प्रणाली",
  "landing.find_perfect_service": "सही सेवा खोजें",
  "landing.near_you_instantly": "आपके आस-पास, तुरंत।",
  "landing.hero_subtitle": "सर्वीज़ आपको शीर्ष-रेटेड दर्जी, ज़ेरॉक्स दुकानें, मैकेनिक और कपड़े धोने की सेवाओं की खोज करने में मदद करता है। हम सबसे अच्छे विकल्प की सिफारिश करने के लिए मूल्य, दूरी और रेटिंग का विश्लेषण करते हैं।",
  "landing.go_to_dashboard": "डैशबोर्ड पर जाएं",
  "landing.get_started_now": "अभी शुरू करें",
  "landing.login_to_account": "खाते में लॉगिन करें",
  "landing.top_rated_services": "शीर्ष रेटेड सेवाएं",
  "landing.join_today_subtitle": "इन अद्भुत स्थानीय दुकानों को बुक करने या उनकी समीक्षा करने के लिए आज ही शामिल हों।",
  "landing.top_pick": "शीर्ष पसंद",
  "shop.reviews": "समीक्षाएं",
  "shop.away": "दूर",
  "landing.login_to_view": "देखने के लिए लॉगिन करें",
  "landing.feature_1_title": "स्मार्ट डिस्कवरी",
  "landing.feature_1_desc": "हमारा एल्गोरिदम दूरी, कीमत और ग्राहक समीक्षाओं को संतुलित करके दुकानों को रैंक करता है।",
  "landing.feature_2_title": "विश्वसनीय समीक्षाएं",
  "landing.feature_2_desc": "स्थानीय ग्राहकों की वास्तविक समीक्षाएं आपको सबसे अच्छा निर्णय लेने में मदद करती हैं।",
  "landing.feature_3_title": "अपना व्यवसाय बढ़ाएं",
  "landing.feature_3_desc": "दुकानदार आसानी से अपनी सेवाओं को सूचीबद्ध कर सकते हैं और आस-पास के ग्राहकों को आकर्षित कर सकते हैं।",
  "landing.how_it_works": "यह कैसे काम करता है",
  "landing.step1_title": "सेवाएं खोजें",
  "landing.step1_desc": "अपने वर्तमान स्थान के आसपास तुरंत स्थानीय दुकानें और सेवाएं खोजें।",
  "landing.step2_title": "तुलना करें और चुनें",
  "landing.step2_desc": "कीमतों, दूरी की तुलना करें और पड़ोसियों की वास्तविक समीक्षाएं पढ़ें।",
  "landing.step3_title": "आसानी से जुड़ें",
  "landing.step3_desc": "अपना काम पूरा करने के लिए दिशा-निर्देश प्राप्त करें या सीधे दुकानदार से संपर्क करें।",
  "landing.about_title": "स्थानीय समुदायों को सशक्त बनाना",
  "landing.about_desc": "सर्वीज़ का जन्म एक सरल विचार से हुआ था: कुशल स्थानीय पेशेवरों और उनकी आवश्यकता वाले लोगों के बीच की खाई को पाटना। हम स्थानीय सेवाओं को सुलभ, पारदर्शी और पूरी तरह से परेशानी मुक्त बनाकर पड़ोस की अर्थव्यवस्थाओं को मजबूत करने में विश्वास करते हैं।",
  "landing.stat_shops": "स्थानीय दुकानें",
  "landing.stat_users": "खुश उपयोगकर्ता",
  "landing.stat_cities": "सक्रिय शहर",
  "landing.stat_rating": "ऐप रेटिंग"
};

const mr = {
  "landing.smart_recommendation": "स्मार्ट सेवा शिफारस प्रणाली",
  "landing.find_perfect_service": "परिपूर्ण सेवा शोधा",
  "landing.near_you_instantly": "तुमच्या जवळील, त्वरित.",
  "landing.hero_subtitle": "सर्व्हिज तुम्हाला टॉप-रेटेड शिंपी, झेरॉक्स दुकाने, मेकॅनिक्स आणि लाँड्री सेवा शोधण्यात मदत करते. सर्वात चांगल्या पर्यायाची शिफारस करण्यासाठी आम्ही किंमत, अंतर आणि रेटिंगचे विश्लेषण करतो.",
  "landing.go_to_dashboard": "डॅशबोर्डवर जा",
  "landing.get_started_now": "आता सुरू करा",
  "landing.login_to_account": "खात्यात लॉग इन करा",
  "landing.top_rated_services": "शीर्ष रेट केलेल्या सेवा",
  "landing.join_today_subtitle": "या अद्भुत स्थानिक दुकानांची नोंदणी करण्यासाठी किंवा त्यांचे पुनरावलोकन करण्यासाठी आजच सामील व्हा.",
  "landing.top_pick": "सर्वोत्तम निवड",
  "shop.reviews": "पुनरावलोकने",
  "shop.away": "दूर",
  "landing.login_to_view": "पाहण्यासाठी लॉग इन करा",
  "landing.feature_1_title": "स्मार्ट डिस्कव्हरी",
  "landing.feature_1_desc": "आमचा अल्गोरिदम अंतर, किंमत आणि ग्राहकांच्या पुनरावलोकनांचे संतुलन राखून दुकानांना रँक देतो.",
  "landing.feature_2_title": "विश्वसनीय पुनरावलोकने",
  "landing.feature_2_desc": "स्थानिक ग्राहकांची वास्तविक पुनरावलोकने आपल्याला सर्वोत्तम निर्णय घेण्यास मदत करतात.",
  "landing.feature_3_title": "तुमचा व्यवसाय वाढवा",
  "landing.feature_3_desc": "दुकानदार सहजपणे त्यांच्या सेवा सूचीबद्ध करू शकतात आणि जवळील ग्राहकांना आकर्षित करू शकतात.",
  "landing.how_it_works": "हे कसे कार्य करते",
  "landing.step1_title": "सेवा शोधा",
  "landing.step1_desc": "तुमच्या सध्याच्या स्थानाभोवती स्थानिक दुकाने आणि सेवा त्वरित शोधा.",
  "landing.step2_title": "तुलना करा आणि निवडा",
  "landing.step2_desc": "किमती, अंतराची तुलना करा आणि शेजाऱ्यांची खरी पुनरावलोकने वाचा.",
  "landing.step3_title": "सहज कनेक्ट व्हा",
  "landing.step3_desc": "दिशानिर्देश मिळवा किंवा तुमचे काम करून घेण्यासाठी थेट दुकानदाराशी संपर्क साधा.",
  "landing.about_title": "स्थानिक समुदायांचे सक्षमीकरण",
  "landing.about_desc": "कुशल स्थानिक व्यावसायिक आणि ज्यांना त्यांची गरज आहे अशा लोकांमधील अंतर कमी करण्याच्या एका सोप्या कल्पनेतून सर्व्हिजचा जन्म झाला. स्थानिक सेवा सुलभ, पारदर्शक आणि पूर्णपणे त्रासमुक्त करून शेजारच्या अर्थव्यवस्था मजबूत करण्यावर आमचा विश्वास आहे.",
  "landing.stat_shops": "स्थानिक दुकाने",
  "landing.stat_users": "आनंदी वापरकर्ते",
  "landing.stat_cities": "सक्रिय शहरे",
  "landing.stat_rating": "अॅप रेटिंग"
};

addTranslations(en, hi, mr);
