const { addTranslations } = require('./addTranslations.cjs');

const en = {
  "admin.total_users": "Total Users",
  "admin.total_shops": "Total Shops",
  "admin.new_users": "New Users",
  "admin.new_shops": "New Shops",
  "admin.manage_users": "Manage Users",
  "admin.manage_shops": "Manage Shops",
  "admin.reports": "Reports & Issues",
  "admin.global_feedback": "Global Feedback",
  "admin.add_user": "+ Add User",
  "admin.user_details": "User Details",
  "admin.role": "Role",
  "admin.anonymous_user": "Anonymous User",
  "admin.no_users_found": "No users found.",
  "admin.add_shop": "+ Add Shop",
  "admin.type": "Type",
  "admin.owner_id": "Owner ID",
  "admin.no_shops_found": "No shops found.",
  "admin.report_details": "Report Details",
  "admin.target": "Target",
  "admin.status": "Status",
  "admin.no_reports_found": "No reports found.",
  "admin.no_feedback": "No feedback available",
  "admin.no_extended_profile": "No extended profile added yet.",
  "admin.no_shops_registered": "No shops registered yet.",
  "admin.shop_details": "Shop Details",
  "admin.category": "Category",
  "admin.rating": "Rating",
  "admin.distance": "Distance (City Center)",
  "admin.add_new_user": "Add New User",
  "admin.customer": "Customer",
  "admin.shopkeeper": "Shopkeeper",
  "admin.admin": "Admin",
  "admin.category_type": "Category Type",
  "admin.contact_details": "Contact Details"
};

const hi = {
  "admin.total_users": "कुल उपयोगकर्ता",
  "admin.total_shops": "कुल दुकानें",
  "admin.new_users": "नए उपयोगकर्ता",
  "admin.new_shops": "नई दुकानें",
  "admin.manage_users": "उपयोगकर्ता प्रबंधित करें",
  "admin.manage_shops": "दुकानें प्रबंधित करें",
  "admin.reports": "रिपोर्ट और समस्याएँ",
  "admin.global_feedback": "वैश्विक प्रतिक्रिया",
  "admin.add_user": "+ उपयोगकर्ता जोड़ें",
  "admin.user_details": "उपयोगकर्ता विवरण",
  "admin.role": "भूमिका",
  "admin.anonymous_user": "अनाम उपयोगकर्ता",
  "admin.no_users_found": "कोई उपयोगकर्ता नहीं मिला।",
  "admin.add_shop": "+ दुकान जोड़ें",
  "admin.type": "प्रकार",
  "admin.owner_id": "मालिक आईडी",
  "admin.no_shops_found": "कोई दुकान नहीं मिली।",
  "admin.report_details": "रिपोर्ट विवरण",
  "admin.target": "लक्ष्य",
  "admin.status": "स्थिति",
  "admin.no_reports_found": "कोई रिपोर्ट नहीं मिली।",
  "admin.no_feedback": "कोई प्रतिक्रिया उपलब्ध नहीं है",
  "admin.no_extended_profile": "अभी तक कोई विस्तृत प्रोफ़ाइल नहीं जोड़ी गई है।",
  "admin.no_shops_registered": "अभी तक कोई दुकान पंजीकृत नहीं है।",
  "admin.shop_details": "दुकान विवरण",
  "admin.category": "श्रेणी",
  "admin.rating": "रेटिंग",
  "admin.distance": "दूरी (शहर केंद्र)",
  "admin.add_new_user": "नया उपयोगकर्ता जोड़ें",
  "admin.customer": "ग्राहक",
  "admin.shopkeeper": "दुकानदार",
  "admin.admin": "व्यवस्थापक",
  "admin.category_type": "श्रेणी प्रकार",
  "admin.contact_details": "संपर्क विवरण"
};

const mr = {
  "admin.total_users": "एकूण वापरकर्ते",
  "admin.total_shops": "एकूण दुकाने",
  "admin.new_users": "नवीन वापरकर्ते",
  "admin.new_shops": "नवीन दुकाने",
  "admin.manage_users": "वापरकर्ते व्यवस्थापित करा",
  "admin.manage_shops": "दुकाने व्यवस्थापित करा",
  "admin.reports": "अहवाल आणि समस्या",
  "admin.global_feedback": "जागतिक अभिप्राय",
  "admin.add_user": "+ वापरकर्ता जोडा",
  "admin.user_details": "वापरकर्ता तपशील",
  "admin.role": "भूमिका",
  "admin.anonymous_user": "निनावी वापरकर्ता",
  "admin.no_users_found": "कोणतेही वापरकर्ते आढळले नाहीत.",
  "admin.add_shop": "+ दुकान जोडा",
  "admin.type": "प्रकार",
  "admin.owner_id": "मालक आयडी",
  "admin.no_shops_found": "कोणतीही दुकाने आढळली नाहीत.",
  "admin.report_details": "अहवाल तपशील",
  "admin.target": "लक्ष्य",
  "admin.status": "स्थिती",
  "admin.no_reports_found": "कोणतेही अहवाल आढळले नाहीत.",
  "admin.no_feedback": "कोणताही अभिप्राय उपलब्ध नाही",
  "admin.no_extended_profile": "अद्याप कोणतीही विस्तारित प्रोफाइल जोडली नाही.",
  "admin.no_shops_registered": "अद्याप कोणतीही दुकाने नोंदणीकृत नाहीत.",
  "admin.shop_details": "दुकानाचे तपशील",
  "admin.category": "श्रेणी",
  "admin.rating": "रेटिंग",
  "admin.distance": "अंतर (शहर केंद्र)",
  "admin.add_new_user": "नवीन वापरकर्ता जोडा",
  "admin.customer": "ग्राहक",
  "admin.shopkeeper": "दुकानदार",
  "admin.admin": "प्रशासक",
  "admin.category_type": "श्रेणी प्रकार",
  "admin.contact_details": "संपर्क तपशील"
};

addTranslations(en, hi, mr);
